# Generated by Django 5.2.3 on 2025-07-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
    ]
