# Generated by Django 5.2.3 on 2025-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='test@test.com', editable=False, max_length=254, unique=True, verbose_name='ایمیل برای ارسال رمز'),
        ),
    ]
