# Generated by Django 5.2.3 on 2025-07-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='وضعیت تأیید'),
        ),
        migrations.AddField(
            model_name='professor',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تأیید'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True, verbose_name='ایمیل برای ارسال رمز'),
        ),
    ]
