# Generated by Django 5.2.3 on 2025-07-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_professor_is_verified_professor_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
