# Generated by Django 5.2.3 on 2025-07-18 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_alter_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='professor',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfessorVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professors.professor')),
            ],
        ),
    ]
