# Generated by Django 5.2.3 on 2025-07-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_professor_hashed_password_professor_is_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='hashed_password',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='professor',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='وضعیت ثبت نام'),
        ),
        migrations.DeleteModel(
            name='ProfessorVerificationCode',
        ),
    ]
