# Generated by Django 5.2.3 on 2025-07-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_remove_professor_email_remove_professor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='first_name',
            field=models.CharField(default='pro', max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(default='pro', max_length=100, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='ثبت\u200cنام کامل شده'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
    ]
