# Generated by Django 5.2.3 on 2025-07-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0010_alter_professor_email_alter_professor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='national_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='personnel_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
