# Generated by Django 5.2.4 on 2025-07-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0011_alter_professor_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='password',
        ),
    ]
