# Generated by Django 5.2.4 on 2025-08-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0012_remove_professor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='verification_code',
        ),
    ]
