# Generated by Django 5.2.4 on 2025-08-10 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0013_remove_professor_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='professor',
            name='national_id',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='personnel_code',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(10, message='Personnel code cannot be more than 10 characters.')]),
        ),
    ]
