# Generated by Django 5.2.4 on 2025-08-18 22:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0014_alter_professor_email_alter_professor_national_id_and_more'),
        ('space_managers', '0010_rename_professor_organizer_event_staff_organizer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Staff',
        ),
    ]
