version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: roomito
      POSTGRES_USER: mahya
      POSTGRES_PASSWORD: qnzmb5773
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app/roomito 
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=roomito.settings
    restart: unless-stopped

volumes:
  postgres_data: