# Generated by Django 5.2.4 on 2025-07-29 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0012_remove_professor_password'),
        ('students', '0009_alter_student_is_approved_alter_student_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('event', 'Event'), ('class', 'Class'), ('gathering', 'Gathering')], max_length=20)),
                ('date', models.DateField()),
                ('reservee_type', models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], max_length=20)),
                ('description', models.CharField(default='no description')),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_review', max_length=20)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_instance', to='space_managers.reservation')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_managers.space')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_instance', to='space_managers.schedule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('class', 'Class'), ('gathering', 'Gathering')], max_length=20)),
                ('date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('organizer', models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], max_length=20)),
                ('description', models.CharField(default='no description')),
                ('professor_organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor')),
                ('student_organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('spaces', models.ManyToManyField(help_text='managed spaces', to='space_managers.space')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='space_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.spacemanager'),
        ),
    ]
