# Generated by Django 5.2.3 on 2025-07-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('space_managers', '0001_initial'),
        ('students', '0002_remove_student_password_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('space_managers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.spacemanager', verbose_name='مدیر فضا')),
            ],
            options={
                'verbose_name': 'فضا',
                'verbose_name_plural': 'فضاها',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('event', 'رویداد'), ('class', 'جلسات درسی'), ('gathering', 'جلسات دورهمی')], max_length=20, verbose_name='نوع رزرو')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('reservee_type', models.CharField(choices=[('student', 'دانشجو'), ('teacher', 'استاد')], max_length=20, verbose_name='نوع رزروکننده')),
                ('status', models.CharField(choices=[('under_review', 'در حال بررسی شدن'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='under_review', max_length=20, verbose_name='وضعیت رزرو')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor', verbose_name='استاد')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='دانشجو')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space', verbose_name='فضا')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
        ),
    ]
