# Generated by Django 5.2.3 on 2025-07-14 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('space_managers', '0002_space_reservation'),
        ('students', '0002_remove_student_password_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spacemanager',
            options={},
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='بدون توضیحات', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor', verbose_name='استاد رزروکننده'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservee_type',
            field=models.CharField(choices=[('student', 'دانشجو'), ('professor', 'استاد')], max_length=20, verbose_name='رزروکننده'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space', verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='دانجوی رزروکننده'),
        ),
        migrations.AlterField(
            model_name='spacemanager',
            name='spaces',
            field=models.TextField(help_text='لیست فضاها', verbose_name='فضاها'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('event_type', models.CharField(choices=[('event', 'رویداد'), ('class', 'جلسه درسی'), ('gathering', 'جلسات دورهمی')], max_length=20, verbose_name='نوع')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/', verbose_name='پوستر')),
                ('organizer', models.CharField(choices=[('student', 'دانشجو'), ('professor', 'استاد')], max_length=20, verbose_name='برگزار کننده')),
                ('description', models.CharField(default='بدون توضیحات', verbose_name='توضیحات')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor', verbose_name='استاد برگزارکننده')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space', verbose_name='محل برگزاری')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='دانجوی برگزارکننده')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='ساعت شروع')),
                ('end_time', models.DateTimeField(verbose_name='ساعت پایان')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space_managers.reservation', verbose_name='رزرو')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_managers.space', verbose_name='محل برگزاری')),
            ],
        ),
    ]
