# Generated by Django 5.2.4 on 2025-08-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0002_create_default_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('hall', 'hall'), ('class', 'Class'), ('labratory', 'Labratory'), ('office', 'Office')], default='hall', max_length=20),
            preserve_default=False,
        ),
    ]
