# Generated by Django 5.2.4 on 2025-08-10 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0003_schedule_date_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='spacemanager',
            name='spaces',
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(default='no description'),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='space',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='space_managers.spacefeature'),
        ),
    ]
