# Generated by Django 5.2.3 on 2025-07-14 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0003_alter_reservation_options_alter_space_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space', verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space', verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='space_managers.reservation', verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_managers.space', verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.spacemanager', verbose_name='مدیر فضا'),
        ),
    ]
