# Generated by Django 5.2.4 on 2025-08-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0003_space_space_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hosting_association',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hosting_organizations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='responsible_organizer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_hour_code',
            field=models.PositiveSmallIntegerField(choices=[(1, '7:00 - 8:00'), (2, '8:00 - 9:00'), (3, '9:00 - 10:00'), (4, '10:00 - 11:00'), (5, '11:00 - 12:00'), (6, '12:00 - 13:00'), (7, '13:00 - 14:00'), (8, '14:00 - 15:00'), (9, '15:00 - 16:00'), (10, '16:00 - 17:00'), (11, '17:00 - 18:00'), (12, '18:00 - 19:00')], default=1, help_text='Hour code (1=7:00-8:00 AM, 2=8:00-9:00 AM, ..., 12=6:00-7:00 PM)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_hour_code',
            field=models.PositiveSmallIntegerField(choices=[(1, '7:00 - 8:00'), (2, '8:00 - 9:00'), (3, '9:00 - 10:00'), (4, '10:00 - 11:00'), (5, '11:00 - 12:00'), (6, '12:00 - 13:00'), (7, '13:00 - 14:00'), (8, '14:00 - 15:00'), (9, '15:00 - 16:00'), (10, '16:00 - 17:00'), (11, '17:00 - 18:00'), (12, '18:00 - 19:00')], default=2, help_text='Hour code (1=7:00-8:00 AM, 2=8:00-9:00 AM, ..., 12=6:00-7:00 PM)'),
            preserve_default=False,
        ),
    ]
