# Generated by Django 5.2.4 on 2025-08-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0004_spacefeature_remove_spacemanager_spaces_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacefeature',
            options={},
        ),
    ]
