# Generated by Django 5.2.3 on 2025-07-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0004_alter_event_space_alter_reservation_space_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='space_managers',
        ),
    ]
