# Generated by Django 5.2.4 on 2025-08-21 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0004_remove_schedule_end_time_remove_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourSlot',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('time_range', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_schedules', to='space_managers.hourslot'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_schedules', to='space_managers.hourslot'),
        ),
    ]
