# Generated by Django 5.2.3 on 2025-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0005_remove_space_space_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال/غیرفعال'),
        ),
        migrations.RemoveField(
            model_name='spacemanager',
            name='spaces',
        ),
        migrations.AddField(
            model_name='spacemanager',
            name='spaces',
            field=models.ManyToManyField(help_text='لیست فضاهای مدیریت شده', to='space_managers.space', verbose_name='فضاها'),
        ),
    ]
