# Generated by Django 5.2.4 on 2025-08-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0006_add_hour_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourslot',
            name='code',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservee_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=20),
        ),
    ]
