# Generated by Django 5.2.3 on 2025-07-15 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0006_schedule_is_active_remove_spacemanager_spaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_active',
        ),
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_instance', to='space_managers.schedule', verbose_name='زمان\u200cبندی رزرو'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_instance', to='space_managers.reservation', verbose_name='رزرو'),
        ),
    ]
