# Generated by Django 5.2.4 on 2025-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0006_reservationnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='no description', max_length=255),
        ),
    ]
