# Generated by Django 5.2.3 on 2025-07-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0007_remove_schedule_is_active_reservation_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemanager',
            name='email',
            field=models.EmailField(default='manager@placeholder.com', max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
