# Generated by Django 5.2.4 on 2025-08-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0007_alter_hourslot_code_alter_reservation_reservee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
