# Generated by Django 5.2.4 on 2025-08-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0007_remove_schedule_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
