# Generated by Django 5.2.3 on 2025-07-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0010_alter_professor_email_alter_professor_first_name_and_more'),
        ('space_managers', '0008_spacemanager_email'),
        ('students', '0009_alter_student_is_approved_alter_student_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
        migrations.AddField(
            model_name='event',
            name='professor_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor'),
        ),
        migrations.AddField(
            model_name='event',
            name='student_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='no description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('event', 'Event'), ('class', 'Class'), ('gathering', 'Gathering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(default='no description'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('event', 'Event'), ('class', 'Class'), ('gathering', 'Gathering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservee_type',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_instance', to='space_managers.schedule'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.space'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_instance', to='space_managers.reservation'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_managers.space'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_managers.spacemanager'),
        ),
        migrations.AlterField(
            model_name='spacemanager',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='spacemanager',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spacemanager',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spacemanager',
            name='spaces',
            field=models.ManyToManyField(help_text='managed spaces', to='space_managers.space'),
        ),
        migrations.AlterField(
            model_name='spacemanager',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
