# Generated by Django 5.2.4 on 2025-08-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0008_reservation_manager_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='no description', max_length=500),
        ),
    ]
