# Generated by Django 5.2.4 on 2025-08-16 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0008_reservation_phone_number_space_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='space_photos/')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='space_managers.space')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
