# space_managers/migrations/0010_event_add_new_fields.py
# Generated by Django 5.2.4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0009_alter_event_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                null=True, blank=True,
                related_name='organized_events'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(null=True, blank=True),
        ),
    ]
