# Generated by Django 5.2.4 on 2025-08-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0009_spaceimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='professor_organizer',
            new_name='staff_organizer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='professor',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservee_type',
            field=models.CharField(choices=[('student', 'Student'), ('Staff', 'Staff')], max_length=20),
        ),
    ]
