# Generated by Django 5.2.4 on 2025-09-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0012_event_cleanup_and_rename'),
        ('staffs', '0002_alter_staff_user'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='event',
            name='student_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
