# Generated by Django 5.2.4 on 2025-09-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0013_event_staff_organizer_event_student_organizer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_description',
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
