# Generated by Django 5.2.4 on 2025-09-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0014_rename_description_event_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
    ]
