# Generated by Django 5.2.4 on 2025-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_managers', '0015_rename_event_description_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='no description'),
        ),
    ]
