# Generated by Django 5.2.4 on 2025-08-19 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('personnel_code', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(10, message='Personnel code cannot be more than 10 characters.')])),
                ('national_id', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('is_registered', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
