# Generated by Django 5.2.4 on 2025-09-16 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_alter_staff_personnel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='personnel_code',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(10, message='Personnel code cannot be more than 10 characters.')]),
        ),
    ]
