from django.urls import path
from .views import (
    ManagerSpaceDeleteView,
    ReservationDetailView,
    SpaceManagerProfileView,
    SpaceListView,
    EventListView,
    EventDetailView,
    SpaceManagerProfileUpdateView,
    SpaceUpdateFeatureView,
    SpaceFeatureView,
    ReservationCreateView,
    ManagerReservationListView,
    SpaceDetailView,
    ManagerSpaceDetailView,
    ManagerSpaceListView,
    ManagerSpaceCreateView,
    ManagerSpaceUpdateView,
    ScheduleAvailabilityView,
    ReservationDecisionView
)

urlpatterns = [
    path("spacemanager/profile/", SpaceManagerProfileView.as_view(), name="space-manager-profile"),
    path("spaces/list/", SpaceListView.as_view(), name="spaces-list"),
    path("events/list/", EventListView.as_view(), name="events-list"),
    path("events/<int:event_id>/", EventDetailView.as_view(), name="event-details"),
    path("spacemanager/updateProfile/", SpaceManagerProfileUpdateView.as_view(), name="space-manager-profile-update"),
    path("<int:space_id>/features", SpaceFeatureView.as_view(), name="space-feature-update"),
    path('<int:space_id>/reserve/', ReservationCreateView.as_view(), name='space_reserve'),
    path('spacemanager/reservations/', ManagerReservationListView.as_view(), name='manager_reservations'),
    path('space/<int:space_id>/', SpaceDetailView.as_view(), name="space-details"),
    path("spacemanager/spaces/", ManagerSpaceListView.as_view(), name="manager-space-list"),
    path("spacemanager/<int:space_id>/", ManagerSpaceDetailView.as_view(), name="manager-space-detail"),
    path('spacemanager/createSpace/', ManagerSpaceCreateView.as_view(), name="create-space"),
    path('spacemanager/<int:space_id>/updateSpace/', ManagerSpaceUpdateView.as_view(), name="update-space"),
    path('schedules/availability/', ScheduleAvailabilityView.as_view(), name='schedule-availability'),
    path('spacemanager/<int:reservation_id>/decision/',ReservationDecisionView.as_view(), name='reservations-desicion'),
    path("spacemanager/reservations/<int:reservation_id>/", ReservationDetailView.as_view(), name="reservation-detail"),
    path("spacemanager/<int:space_id>/delete/", ManagerSpaceDeleteView.as_view(), name="space-delete"),
    ]
