# Generated by Django 5.2.3 on 2025-07-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='شماره دانشجویی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل')),
                ('student_card_photo', models.ImageField(upload_to='student_cards/', verbose_name='عکس کارت دانشجویی')),
                ('password', models.CharField(max_length=128, verbose_name='رمز عبور')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
            },
        ),
    ]
