# Generated by Django 5.2.3 on 2025-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='وضعیت تأیید'),
        ),
    ]
