# Generated by Django 5.2.3 on 2025-07-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_email_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='default_password', max_length=128, verbose_name='رمز عبور'),
            preserve_default=False,
        ),
    ]
