# Generated by Django 5.2.4 on 2025-08-10 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_is_approved_alter_student_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MaxLengthValidator(12, message='student ID cannot be more than 10 characters.')]),
        ),
    ]
